services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network
  server:
    container_name: spring-server
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ..:/workspace

networks:
  app-network:
